listen: 0.0.0.0:443

vhosts:
  ##V2RAY@- name: FAKEV2DOMAIN
    ##V2RAY@tlsoffloading: true
    ##V2RAY@managedcert: true
    ##V2RAY@alpn: h2,http/1.1
    ##V2RAY@protocols: tls12,tls13
    ##V2RAY@http:
      ##V2RAY@handler: fileServer
      ##V2RAY@args: /var/www/html
    ##V2RAY@default:
      ##V2RAY@handler: proxyPass
      ##V2RAY@args: unix:/tmp/v2ray-ds/v2ray.sock

  ##SUBAPI@- name: FAKEAPIDOMAIN
    ##SUBAPI@tlsoffloading: true
    ##SUBAPI@managedcert: true
    ##SUBAPI@alpn: http/1.1
    ##SUBAPI@protocols: tls12,tls13
    ##SUBAPI@http:
      ##SUBAPI@handler: proxyPass
      ##SUBAPI@args: 127.0.0.1:25500

  ##MTPROTO@- name: FAKEMTDOMAIN
    ##MTPROTO@tlsoffloading: false
    ##MTPROTO@default:
      ##MTPROTO@handler: proxyPass
      ##MTPROTO@args: 127.0.0.1:3128